name: direct
channels:
  - conda-forge
  - plotly
  - defaults
dependencies:
  - appnope
  - asn1crypto
  - attrs
  - backcall
  - blas
  - bleach
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - chart-studio
  - cryptography
  - cycler
  - decorator
  - defusedxml
  - entrypoints
  - freetype
  - idna
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - joblib
  - json5
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyterlab
  - jupyterlab_server
  - kiwisolver
  - libcxx
  - libcxxabi
  - libedit
  - libffi
  - libgfortran
  - libpng
  - libsodium
  - llvm-openmp
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - nbconvert
  - nbformat
  - ncurses
  - notebook
  - numpy
  - numpy-base
  - openssl
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - pexpect
  - pickleshare
  - pip
  - plotly
  - plotly-geo
  - plotly-orca
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - ptyprocess
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pytz
  - pyzmq
  - readline
  - requests
  - retrying
  - scikit-learn
  - scipy
  - send2trash
  - setuptools
  - six
  - sqlite
  - terminado
  - testpath
  - tk
  - tornado
  - traitlets
  - urllib3
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - xz
  - zeromq
  - zipp
  - zlib


